name: Update index.html with current time

on:
    push:
        branches: [ main ]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/Setup-python@v3
          with:
            python-version: 3.11
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install pytest
            if [ -f requirements.txt]; then pip install -r requirements.txt; fi
        
        - name: Run Python script
          run: |
            python update_time.py
        
        - name: Commit updated index.html
          uses: EndBug/add-and-commit@v7
          with:
            author_name: www3drbiz
            author_email: www3drbiz@gmail.com
            message: Update index.html with current time
            add: "index.html"
            